### PR TITLE
Fix tests and activate linting for CI

### LINKED ISSUE #19: tests fail with inspec 0.9.5
```interactive
$ .bin/rake test
/Users/stephan/.rbenv/versions/2.2.3/bin/ruby -I/Users/stephan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib:/Users/stephan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib /Users/stephan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Kitchen::Verifier::Inspec
  verifier api_version is 1
  plugin_version is set to Kitchen::Verifier::INSPEC_VERSION
  with an ssh transport
    constructs a Inspec::Runner using transport config data and state (FAILED - 1)
    adds *spec.rb test files to runner (FAILED - 2)
    calls #run on the runner (FAILED - 3)
  with an winrm transport
    constructs a Inspec::Runner using transport config data and state (FAILED - 4)
  with an unsupported transport
    #call raises a UserError

Failures:

  1) Kitchen::Verifier::Inspec with an ssh transport constructs a Inspec::Runner using transport config data and state
     Failure/Error: raise ActionFailed, "Inspec Runner returns #{exit_code}" unless exit_code == 0
     
     Kitchen::ActionFailed:
       Inspec Runner returns 
     # ./lib/kitchen/verifier/inspec.rb:57:in `call'
     # ./spec/kitchen/verifier/inspec_spec.rb:163:in `block (3 levels) in <top (required)>'

  2) Kitchen::Verifier::Inspec with an ssh transport adds *spec.rb test files to runner
     Failure/Error: raise ActionFailed, "Inspec Runner returns #{exit_code}" unless exit_code == 0
     
     Kitchen::ActionFailed:
       Inspec Runner returns 
     # ./lib/kitchen/verifier/inspec.rb:57:in `call'
     # ./spec/kitchen/verifier/inspec_spec.rb:177:in `block (3 levels) in <top (required)>'

  3) Kitchen::Verifier::Inspec with an ssh transport calls #run on the runner
     Failure/Error: raise ActionFailed, "Inspec Runner returns #{exit_code}" unless exit_code == 0
     
     Kitchen::ActionFailed:
       Inspec Runner returns 
     # ./lib/kitchen/verifier/inspec.rb:57:in `call'
     # ./spec/kitchen/verifier/inspec_spec.rb:184:in `block (3 levels) in <top (required)>'

  4) Kitchen::Verifier::Inspec with an winrm transport constructs a Inspec::Runner using transport config data and state
     Failure/Error: raise ActionFailed, "Inspec Runner returns #{exit_code}" unless exit_code == 0
     
     Kitchen::ActionFailed:
       Inspec Runner returns 
     # ./lib/kitchen/verifier/inspec.rb:57:in `call'
     # ./spec/kitchen/verifier/inspec_spec.rb:228:in `block (3 levels) in <top (required)>'

Finished in 0.08909 seconds (files took 0.16373 seconds to load)
7 examples, 4 failures

Failed examples:

rspec ./spec/kitchen/verifier/inspec_spec.rb:140 # Kitchen::Verifier::Inspec with an ssh transport constructs a Inspec::Runner using transport config data and state
rspec ./spec/kitchen/verifier/inspec_spec.rb:166 # Kitchen::Verifier::Inspec with an ssh transport adds *spec.rb test files to runner
rspec ./spec/kitchen/verifier/inspec_spec.rb:180 # Kitchen::Verifier::Inspec with an ssh transport calls #run on the runner
rspec ./spec/kitchen/verifier/inspec_spec.rb:213 # Kitchen::Verifier::Inspec with an winrm transport constructs a Inspec::Runner using transport config data and state

/Users/stephan/.rbenv/versions/2.2.3/bin/ruby -I/Users/stephan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib:/Users/stephan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib /Users/stephan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

### PR DESCRIPTION
**Pull request by srenatus**
...such that [this](https://github.com/chef/kitchen-inspec/blob/sr/fix19/lib/kitchen/verifier/inspec.rb#L57) doesn't fire. Fixes #19.

### CODE REVIEW

**Comment by chris-rock** [comment]
@srenatus Why does it fire an exit_status?

**Comment by srenatus** [comment]
@chris-rock If `runner.run` doesn't return 0, an exception will be raised at the end of [`verifier.call()`](https://github.com/chef/kitchen-inspec/blob/sr/fix19/lib/kitchen/verifier/inspec.rb#L39) because the mock doesn't return anything unless told explicitly:

```ruby
exit_code = runner.run
raise ActionFailed, "Inspec Runner returns #{exit_code}" unless exit_code == 0
```

This was [added recently](https://github.com/chef/kitchen-inspec/commit/391832a04080610f37042f3cf9f9cfbc7b32252e), I'm just adapting the tests.

**Comment by chris-rock** [comment]
- added inspec ruby styling
- fixed lint errors
- activated lint as default rake task

**Comment by arlimus** [comment]
This is a huge quality improvement, wow!! Excellent :confetti_ball: @srenatus and @chris-rock :+1:

**Pull request merged**
