### PR TITLE
deduplicate Gemfiles

### PR DESCRIPTION
**Pull request by srenatus**
Let's see if this works... :)

Apparently, it does. LGTM

### CODE REVIEW

**Comment by chris-rock** [comment]
should we try Bundler 1.12 instead https://github.com/bundler/bundler/issues/4046?

**Comment by srenatus** [comment]
@chris-rock But we cannot really determine which version of bundler is used, right? Bundler isn't in the Gemfile...

**Comment by chris-rock** [comment]
this should only be relevant in ci, otherwise user will install kitchen-inspec via `gem install kitchen-inspec` where no bundler is required.

**Comment by chris-rock** [comment]
let me try it, one PR will make it ;-)

**Comment by chris-rock** [comment]
#42

**Pull request merged**
