### PR TITLE
Specify inspec output format from kitchen.yml

### PR DESCRIPTION
**Pull request by cheesesashimi**
This implements https://github.com/chef/kitchen-inspec/issues/26

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @cheesesashimi

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by irvingpop** [comment]
thanks for adding this @cheesesashimi !     We'll need to get you added to the IBM CCLA in order to satisfy currybot.

One bit of feedback, I'm surprised the test here didn't break:  https://github.com/chef/kitchen-inspec/blob/master/spec/kitchen/verifier/inspec_spec.rb#L145  -  recommend some additional test coverage for specifying a formatter

Also paging @chris-rock for review

**Comment by chris-rock** [comment]
@cheesesashimi Thanks for this great addition. This is a great user-facing improvement. Could you add a test to verify that the format is set properly. I am also thinking about adding some documentation about the available flags. What do you think. Let me know if you need help.

@irvingpop This is caused by the fact, that format is optional. Could you make sure with @cheesesashimi that we have a CCLA or CLA signed?

**Comment by cheesesashimi** [comment]
@chris-rock I'll write a test to verify correct formatting and I'd appreciate any feedback once I've attached it since I admit I'm pretty new to Ruby and rspec, in general :). As far as available flags are concerned, aside from --format, --id is another one that I could see someone setting through an env variable provided from their CI system. I'm happy to add that to this pull request as well.

@irvingpop I received an e-mail confirmation that I was added to IBM's CCLA, so I should be good to go unless I also need a signed ICLA as well?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by chris-rock** [comment]
@cheesesashimi Thanks for adding the test. Lets tackle the id in another PR.

**Pull request merged**
