### PR TITLE
Add support for profiles_path

### PR DESCRIPTION
**Pull request by brettlangdon**
Address #66 

For this change we are adding the ability to pass through `profiles_path` from `.kitchen.yml` into the `Inspec::Runner`.

Example `verifier` for `.kitchen.yml`:

```yaml
---
verifier:
  name: inspec
  profiles_path: repo/path/to/profiles
```

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @brettlangdon

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by brettlangdon** [comment]
The test failures are due to RuboCop offenses for class length and assignment branch condition. How would you like me to resolve?

Here are the offenses:

```
Offenses:
lib/kitchen/verifier/inspec.rb:33:5: C: Class has too many lines. [101/100]
    class Inspec < Kitchen::Verifier::Base
    ^^^^^
lib/kitchen/verifier/inspec.rb:101:7: C: Assignment Branch Condition size for runner_options is too high. [36.89/33]
      def runner_options(transport, state = {})
      ^^^
```

**Comment by chris-rock** [comment]
Hi @brettlangdon Thanks for the addition. Is this providing any additional value to:

```
suites:
  - name: contains_inspec
    run_list:
      - recipe[os_prepare]
    verifier:
      inspec_tests:
        - https://github.com/nathenharvey/tmp_compliance_profile
```
This was added to kitchen-inspec in #63. `inspec_tests` are the same as inspec input paramets

**Comment by brettlangdon** [comment]
Yeah, what I am trying to do is reference local profiles.

Basically try to get over this error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [You must supply a --profiles-path to inherit from other profiles.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Some more context from me might also help. This is my `.kitchen.yml`:

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  profiles_path: test/profiles

platforms:
  - name: ubuntu-14.04

suites:
  - name: base
    run_list:
      - role[base]
```

And the directory structure looks like this:

```
.kitchen.yml
test
├── integration
│   ├── <suite-name>
│   │   └── *_spec.rb
└── profiles
    └── <profile>
        ├── README.md
        ├── controls
        │   ├── *.rb
        └── inspec.yml
```

**Comment by chris-rock** [comment]
Yeah, that is great. We will add a proper dependency resolution to inspec soon. That solves the problem in general :-)

**Comment by brettlangdon** [comment]
\0/ yay.

Any idea on timeline for dependency resolution? And anything I can good to help out there?

**Comment by chris-rock** [comment]
I assume it will become mid-may :-(

**Comment by brettlangdon** [comment]
Ok, is this the issue I should follow? https://github.com/chef/inspec/issues/533

**Comment by chris-rock** [comment]
@brettlangdon yes, exactly!

**Comment by brettlangdon** [comment]
Thanks, I am content if you want to close this issue, or leave open until it is resolved. Your call.

**Comment by chris-rock** [comment]
I merge asap

**Comment by brettlangdon** [comment]
\0/ :D thanks @chris-rock

**Pull request merged**
